apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mall-web
  name: mall-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-web
  template:
    metadata:
      labels:
        app: mall-web
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "mallweb"
        dapr.io/app-port: "8080"
        dapr.io/config: "appconfig"
    spec:
      containers:
      - image: jamesxpenn/mall-web:v2
        name: mall-web
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mall-web
  name: mall-web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mall-web
  type: LoadBalancer
        
